all:
  hosts:
    windows:
      ansible_host: "{{ windows_host }}"
      ansible_port: 5986
      ansible_user: soloman.weng
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_winrm_server_cert_validation: ignore
    ubuntu:
      ansible_host: localhost
      ansible_connection: local
