#!/usr/bin/env bash

set -e

install_ansible () {
  if test ! $(which ansible)
  then
    echo "install ansible..."
    sudo apt install -y ansible
  fi
}


install_ansible

windows_host=$(cat /etc/resolv.conf|grep nameserver|awk '{ print $2 }')

# options: --tags wsl, --tags windows
ansible-playbook -i $(dirname $0)/hosts.yml --ask-become-pass --ask-pass -vv $(dirname $0)/setup.yml -e ansible_host=${windows_host}

echo 'All installed!'
