#!/usr/bin/env bash

set -e

homebrew () {
  if test ! $(which brew)
  then
    echo "install homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

base_homebrew_packages () {
  if [[ -z "$(brew ls --versions ansible)" ]]
  then
    brew install ansible
  fi

  if [[ -z "$(brew tap | grep caskroom/cask)" ]]
  then
    brew tap caskroom/cask
  fi
}



homebrew
base_homebrew_packages

ansible-playbook --ask-sudo-pass -vv setup.yml

echo 'All installed!'
