#!/usr/bin/env bash

set -e

install_ansible () {
  if test ! $(which ansible)
  then
    echo "install ansible..."
    sudo apt install -y ansible 
  fi
}


install_ansible

ansible-playbook --ask-become-pass -vv $(dirname $0)/setup.yml

echo 'All installed!'
