---
- name: install apt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - awscli
    - coreutils
    - grc
    - siege
    - tig
    - vim

- name: install oh-my-zsh
  include: oh_my_zsh.yml

- name: install whalebrew with related tools
  include: whalebrew.yml

- name: vim setup
  include: vim.yml

- name: git setup
  include: git.yml
