---
- name: setup .vimrc file
  copy:
    src: vimrc
    dest: "{{ pref_dir }}/.vimrc"
    mode: 0644

- name: link .vimrc file
  file:
    src: "{{ pref_dir }}/.vimrc"
    dest: ~/.vimrc
    state: link
