" Enable tab space for programming
set tabstop=8
set expandtab
set shiftwidth=4
set softtabstop=4

" Enable comment style vim setting in file level
set modeline

" Enable syntax light
syntax enable

" Set right color scheme
colorscheme desert
set background=dark

" Set UTF8 as default encoding
set encoding=utf8

" Use Unix as standard file type
set ffs=unix,mac,dos

" This is required for vim inside wsl2
" https://github.com/microsoft/terminal/issues/4335
if &term =~ '^xterm'
  " enter vim
  autocmd VimEnter * silent !echo -ne "\e[1 q"
  " oherwise
  let &t_EI .= "\<Esc>[1 q"
  " insert mode
  let &t_SI .= "\<Esc>[5 q"
  " 1 or 0 -> blinking block
  " 2 -> solid block
  " 3 -> blinking underscore
  " 4 -> solid underscore
  " Recent versions of xterm (282 or above) also support

  " 5 -> blinking vertical bar
  " 6 -> solid vertical bar
  " leave vim
  autocmd VimLeave * silent !echo -ne "\e[5 q"
endif
