---
- name: setup aliases dir
  file:
    dest: "{{ alias_dir }}"
    state: directory

- name: link alias zsh files
  file:
    src: "{{playbook_dir}}/roles/ubuntu/files/{{ item }}.zsh"
    dest: "{{ alias_dir }}/{{ item }}.zsh"
    state: link
  with_items:
    - docker
    - utils
