---
- name: install whalebrew
  become: yes
  get_url:
    url: https://github.com/soloman1124/whalebrew/releases/download/0.1.1/whalebrew_linux_amd64
    dest: /usr/local/bin/whalebrew
    mode: 0755

- name: install whalebrew packages
  become: yes
  command: whalebrew install {{ item.image }} -y -n {{ item.name }}
  ignore_errors: yes
  with_items:
    - name: shellcheck
      image: whalebrew/shellcheck
    - name: speedtest
      image: whalebrew/speedtest
    - name: hugo
      image: whalebrew/hugo
    - name: ag
      image: whalebrew/the_silver_searcher
    - name: awslogs
      image: whalebrew/awslogs
    - name: figlet
      image: whalebrew/figlet
    - name: yapf
      image: quay.io/intellihr/whalebrew-yapf:0.30.0
    - name: yarn
      image: quay.io/intellihr/whalebrew-yarn:1.22.5
    - name: ptpython
      image: quay.io/intellihr/whalebrew-ptpython:0.41
    - name: http
      image: quay.io/intellihr/whalebrew-httpie:0.9.9
    - name: jq
      image: whalebrew/jq
    - name: cargo
      image: quay.io/intellihr/whalebrew-cargo:1.37.0
    - name: crystal
      image: quay.io/intellihr/whalebrew-crystal:0.31.0
