---
- name: install chocolatey apps
  win_chocolatey:
    state: present
    name:
    - altair-graphql
    - GoogleChrome
    - insomnia-rest-api-client
    - jetbrainstoolbox
    - notion
    - openvpn
    - powertoys
    - sharex
    - slack

- name: install chocolately apps (pre)
  win_chocolatey:
    allow_prerelease: true
    state: present
    name:
    - microsoft-windows-terminal

# limit wsl2 docker resource
# https://github.com/microsoft/WSL/issues/4166
- name: limit wsl2 memory usage and cpu cores
  win_copy:
    src: files/.wslconfig
    dest: "{{ ansible_env.USERPROFILE }}\\.wslconfig"
    force: true
