---
- name: install atom
  homebrew_cask: name=atom state=present

- name: setup atom preference folder
  copy:
    src: atom/
    dest: "{{ pref_dir }}/atom"

- name: link .atom file
  file:
    src: "{{ pref_dir }}/atom"
    dest: ~/.atom
    state: link

- name: install atom packages
  apm: name={{ item }} state=latest
  with_items:
    - file-icons
    - atom-beautify
    - minimap
    - merge-conflicts
    - zen
    - advanced-open-file
    - atom-material-ui
    - autocomplete-paths
    - vim-mode-plus
    - relative-numbers
