---
- name: check if atom is installed
  command: dpkg-query -W atom
  register: atom_check_deb
  failed_when: atom_check_deb.rc > 1
  changed_when: atom_check_deb.rc == 1

- name: install atom
  become: yes
  apt:
    state: present
    deb: https://atom.io/download/deb
  when: atom_check_deb.rc == 1

- name: setup atom preference folder
  copy:
    src: atom/
    dest: "{{ pref_dir }}/atom"

- name: link .atom file
  file:
    src: "{{ pref_dir }}/atom"
    dest: ~/.atom
    state: link

- name: install atom packages
  apm: name={{ item }} state=latest
  with_items:
    - file-icons
    - atom-beautify
    - minimap
    - vim-mode-plus
    - relative-numbers
    - merge-conflicts
    - zen
    - advanced-open-file
    - split-diff
    - pretty-json
    - tree-view-copy-relative-path
    - autocomplete-python-jedi
