---
- name: add docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: add Docker APT repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} edge
- name: install docker
  become: yes
  apt:
    name: docker-ce
- name: enable docker when reboot
  systemd:
    name: docker
    state: started
    enabled: True
- name: install docker-compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

# the following manage docker as non-root user as: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user
- name: add docker group
  become: yes
  group:
    name: docker
    state: present

- name: get current user
  become: no
  command: whoami
  register: current_user

- name: add current user to docker group
  become: yes
  user:
    name: "{{ current_user.stdout }}"
    groups: docker
    state: present
    append: yes
