---
- name: check font already installed - hack
  stat:
    path:  "{{ font_dir }}/Hack"
  register: font_hack_check
- name: ensure font folder - hack
  become: yes
  file:
    path: "{{ font_dir }}/Hack"
    state: directory
    mode: 0644
  when: not font_hack_check.stat.exists
- name: install fonts - hack
  unarchive:
    src: https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip
    dest: "{{ font_dir }}/Hack"
    remote_src: yes
  register: font_hack_install
  when: not font_hack_check.stat.exists

- name: check font already installed - SourceCodePro
  find: paths="{{ font_dir }}/SourceCodePro" file_type=directory patterns="*.ttf"
  register: font_source_code_pro_check
- name: ensure font folder - SourceCodePro
  become: yes
  file:
    path: "{{ font_dir }}/SourceCodePro"
    state: directory
    mode: 0644
  when: font_source_code_pro_check.matched|int == 0
- name: install fonts - SourceCodePro
  become: yes
  get_url:
    url: "{{ item.url }}"
    dest: "{{ font_dir }}/SourceCodePro/{{ item.file }}"
    remote_src: yes
  with_items:
    - file: SourceCodeVariable-Roman.ttf
      url: https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.ttf
    - file: SourceCodeVariable-Italic.ttf
      url: https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Italic.ttf
  register: font_source_code_pro_install
  when: font_source_code_pro_check.matched|int == 0

- name: update font cache
  command: fc-cache -fv
  become: yes
  when: font_source_code_pro_install.changed or font_hack_install.changed
