---
- name: check if {{ item.app }} is installed
  command: dpkg-query -W {{ item.app }}
  register: app_check_deb
  failed_when: app_check_deb.rc > 1
  changed_when: app_check_deb.rc == 1
- name: install {{ item.app }} (deb)
  become: yes
  apt:
    state: present
    deb: "{{ item.deb }}"
  when: item.deb is defined and app_check_deb.rc == 1
- name: install {{ item.app }} (package)
  become: yes
  apt:
    state: present
    name: "{{ item.package }}"
  when: item.package is defined
