---
- name: check if {{ item.app }} is installed (deb)
  command: dpkg-query -W {{ item.app }}
  register: app_check_deb
  failed_when: app_check_deb.rc > 1
  changed_when: app_check_deb.rc == 1
  when: item.deb is defined
- name: check if {{ item.app }} is installed (snap)
  command: snap list {{ item.app }}
  register: app_check_snap
  failed_when: app_check_snap.rc > 1
  changed_when: app_check_snap.rc == 1
  when: item.snap is defined

- name: install {{ item.app }} (deb)
  become: yes
  apt:
    state: present
    deb: "{{ item.deb }}"
  when: item.deb is defined and app_check_deb.rc == 1
- name: install {{ item.app }} (package)
  become: yes
  apt:
    state: present
    name: "{{ item.package }}"
  when: item.package is defined
- name: install {{ item.app }} (snap)
  become: yes
  command: snap install {{ item.snap }} --classic
  when: item.snap is defined and app_check_snap.rc == 1
