---
- name: use homebrew cask versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install common apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - alfred
    - atom
    - calibre
    - dropbox
    - firefox
    - gitter
    - google-chrome
    - iterm2-beta
    - mplayerx
    - thunder
    - ynab

- name: install fonts
  include: fonts.yml
