---
- name: setup target build folder
  file:
    path: "{{ build_dir }}"
    state: directory
    mode: 0755

- name: setup code folder
  file:
    path: "{{ code_dir }}"
    state: directory
    mode: 0755

- name: setup font folder
  file:
    path: "{{ font_dir }}"
    state: directory
    mode: 0755
